[window]
dynamic_padding = true
decorations = 'buttonless'

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/alacritty-theme/themes/oxocarbon.toml",
]

# root stuff
working_directory = "/home/chazzox"
